server:
  servlet:
    context-path: /media
  port: 63050
spring:
  application:
    name: media-api
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xc402_media?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: abc123
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
  mvc: #因为Springfox 使用的路径匹配是基于AntPathMatcher的，而Spring Boot 2.6.X使用的是PathPatternMatcher
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
#  config: classpath:log4j2-dev.xml
  level:
    root: info
swagger:
  title: "媒资管理系统"
  description: "媒资系统管理系统对课程相关信息进行管理"
  base-package: com.xuecheng.media
  enabled: true
  version: 1.0.0
minio:
  endpoint: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucket:
    files: mediafiles
    videofiles: video


